CREATE TABLE IF NOT EXISTS pilots
               (
                [year] int not null,
                xc_rank int not null, 
                username, 
                pilot_id);

CREATE TABLE IF NOT EXISTS flights
            (pilot_id, flight_id, launch,flight_type,flight_length,flight_points, glider, details);

CREATE TABLE IF NOT EXISTS gliders
            (glider TEXT PRIMARY KEY,class TEXT, glider_norm TEXT,UNIQUE (glider COLLATE NOCASE));


CREATE TEMPORARY TABLE temp_gliders(glider, class, glider_norm);
INSERT INTO temp_gliders(glider,glider_norm,class)
VALUES
('OZONE Alpina 4','OZONE Alpina 4','C'),
('OZONE Photon','OZONE Photon','C'), --2liner
('AIRDESIGN Volt 4','AIRDESIGN Volt 4','C'), --2liner
('NIVIUK Artik R','NIVIUK Artik R','C'),
('OZONE Delta 4','OZONE Delta 4','C'),
('ADVANCE Sigma 11','ADVANCE Sigma 11','C'),
('NOVA MENTOR 7 light','NOVA MENTOR 7 light','B'),
('FLOW PARAGLIDERS Fusion','FLOW Fusion','C'),
('NIVIUK Artik 6','NIVIUK Artik 6','C'),
('ADVANCE Iota DLS','ADVANCE Iota DLS','B'),
('OZONE Rush 6','OZONE Rush 6','B'),
('SUPAIR Savage','SUPAIR Savage','C'),
('SKYWALK Mint','SKYWALK Mint','C'), --2liner
('GIN GLIDERS Bonanza 2','GIN Bonanza 2','C'),
('GIN GLIDERS Bonanza 3','GIN Bonanza 3','C'), --2liner
('OZONE SwiftSix','OZONE SwiftSix','B'),
('OZONE Delta 3','OZONE Delta 3','C'),
('OZONE Alpina 3','OZONE Alpina 3','C'),
('PHI Maestro 2 light','PHI Maestro 2 light','B'),
('OZONE Swift 5','OZONE Swift 5','B'),
('ADVANCE Sigma 10','ADVANCE Sigma 10','C'),
('GIN GLIDERS Camino','GIN Camino','C'),
('GIN GLIDERS Explorer 2','GIN Explorer 2','B'),
('PHI Allegro X-alps','PHI Allegro Xalps','C'),
('NIVIUK Ikuma 2','NIVIUK Ikuma 2','B'),
('SKYWALK Chili 5','SKYWALK Chili 5','B'),
('OZONE Rush 5','OZONE Rush 5','B'),
('PHI Maestro 2','PHI Maestro 2','B'),
('BGD Base 2','BGD Base 2','B'),
('ADVANCE Iota 2','ADVANCE Iota 2','B'),
('BGD Cure 2','BGD Cure 2','C'),
('PHI Maestro','PHI Maestro','B'),
('NIVIUK Artik 5','NIVIUK Artik 5','C'),
('ADVANCE XI','ADVANCE XI','B'),
('SKYWALK Arak','SKYWALK Arak','B'),
('SKYWALK Arak Air','SKYWALK Arak Air','B'),
('MAC PARA Eden 7','MACPARA Eden 7','B'),
('AIRDESIGN Soar','AIRDESIGN Soar','B'),
('AXIS Venus SC','AXIS Venus SC','C'),
('GIN GLIDERS Explorer','GIN Explorer','B'),
('PHI Maestro X-alps','PHI Maestro Xalps','B'),
('TRIPLE SEVEN Rook 3','777 Rook 3','B'),
('NOVA Sector','NOVA Sector','C'),
('NOVA Mentor 5','NOVA Mentor 5','B'),
('FLOW PARAGLIDERS Fusion Light','FLOW Fusion Light','C'),
('ADVANCE Epsilon 9','ADVANCE Epsilon 9','B'),
('UP Trango X-race','UP Trango X-race','C'),
('SKYWALK Chili 4','SKYWALK Chili 4','B'),
('MAC PARA Elan 3','MACPARA Elan 3','C'),
('BGD Base 2 Lite','BGD Base 2 Lite','B'),
('SKYWALK Cayenne 6','SKYWALK Cayenne 6','C'),
('TRIPLE SEVEN Queen 2','777 Queen 2','C'),
('OZONE Delta 2','OZONE Delta 2','C'),
('PHI Beat Light','PHI Beat Light','B'),
('AIRDESIGN Rise 4','AIRDESIGN Rise 4','B'),
('ADVANCE Iota','ADVANCE Iota','B'),
('PHI Allegro','PHI Allegro','C'),
('NIVIUK Ikuma 2 P','NIVIUK Ikuma 2 P','B'),
('NOVA Mentor 6','NOVA Mentor 6','B'),
('UP Trango X','UP Trango X','C'),
('NIVIUK Hook 5','NIVIUK Hook 5','B'),
('AIRDESIGN Volt 3','AIRDESIGN Volt 3','C'),
('BGD Cure','BGD Cure','C'),
('SKYWALK Cumeo','SKYWALK Cumeo','B'),
('OZONE Buzz Z6','OZONE Buzz Z6','B'),
('NOVA Mentor 4','NOVA Mentor 4','B'),
('OZONE Geo 6','OZONE Geo 6','B'),
('PHI Beat','PHI Beat','B'),
('OZONE Rush 4','OZONE Rush 4','B'),
('SWING Nyos RS','SWING Nyos RS','B'),
('MAC PARA Elan 2','MACPARA Elan 2','C'),
('ADVANCE Epsilon 8','ADVANCE Epsilon 8','B'),
('DRIFT Hawk','DRIFT Hawk','B'),
('DAVINCI Tango','DAVINCI Tango','C'),
('NOVA Ion 6','NOVA Ion 6','B'),
('OZONE Alpina 2','OZONE Alpina 2','C'),
('UP Kangri','UP Kangri','B'),
('BGD Punk','BGD Punk','B'),
('SKYWALK Cayenne 5','SKYWALK Cayenne 5','C'),
('FLOW PARAGLIDERS Freedom 2','FLOW Freedom 2','B'),
('OZONE Swift 4','OZONE Swift 4','B'),
('SWING Helios RS','SWING Helios RS','C'),
('SKYWALK Tequila 5','SKYWALK Tequila 5','B'),
('NIVIUK Hook 6','NIVIUK Hook 6','B'),
('UP Summit XC4','UP Summit XC4','B'),
('NOVA Ion 5','NOVA Ion 5','B'),
('NIVIUK Artik 4','NIVIUK Artik 4','C'),
('BGD Lynx 2','BGD Lynx 2','C'), -- 2liner
('NOVA Phantom','NOVA Phantom','B'),
('PHI Tenor Light','PHI Tenor Light','B'),
('SKYWALK Cumeo 2','SKYWALK Cumeo 2','B'),
('ADVANCE Epsilon DLS','ADVANCE Epsilon DLS','B'),
('BGD Base','BGD Base','B'),
('SWING Nyos 2 RS','SWING Nyos 2 RS','B'),
('BGD Lynx','BGD Lynx','C'), 
('GIN Explorer 2','GIN Explorer 2','B'),
('PHI Tenor','PHI Tenor','B'),
('SUPAIR Step','SUPAIR Step','B'),
('NOVA Ion 4','NOVA Ion 4','B'),
('GRADIENT Aspen 6','GRADIENT Aspen 6','C'),
('SWING Libra RS','SWING Libra RS','C'),
('UP Kibo 2','UP Kibo 2','B'),
('GRADIENT Nevada 2','GRADIENT Nevada 2','B'),
('AXIS Vega 6','AXIS Vega 6','C'),
('OZONE Swift 6','OZONE SwiftSix','B'),
('SUPAIR Step Light','SUPAIR Step Light','B'),
('PROFLY Leeloo','PROFLY Leeloo','B'),
('NIVIUK Hook 5 P','NIVIUK Hook 5 P','B'),
('NOVA Mentor 5 light','NOVA Mentor 5 light','B'),
('TRIPLE SEVEN Q-light','777 Qlight','C'),
('SKYWALK Masala 3','SKYWALK Masala 3','A'),
('PHI Symphonia 2','PHI Symphonia 2','A'),
('GIN GLIDERS Calypso','GIN Calypso','B'),
('NOVA Ion 6 Light','NOVA Ion 6 Light','B'),
('GIN GLIDERS Carrera plus','GIN Carrera plus','B'),
('NOVA Mentor 6 Light','NOVA Mentor 6 Light','B'),
('OZONE Buzz Z5','OZONE Buzz Z5','B'),
('DRIFT Merlin','DRIFT Merlin','C'),
('SUPAIR Taska','SUPAIR Taska','C'),
('AIRDESIGN Rise 3','AIRDESIGN Rise 3','B'),
('TRIPLE SEVEN Knight','777 Knight','B'),
('SKYWALK Spice 2','SKYWALK Spice 2','C'),
('NOVA Ion 5 light','NOVA Ion 5 light','B'),
('ADVANCE Alpha 6','ADVANCE Alpha 6','A'),
('Ozone Alpina4','OZONE Alpina 4','C'),
('BGD Epic','BGD Epic','B'),
('BGD Epic 2','BGD Epic 2','B'),
('ADVANCE Alpha 7','ADVANCE Alpha 7','A'),
('SKYWALK Tequila 4','SKYWALK Tequila 4','B'),
('ADVANCE Sigma 9','ADVANCE Sigma 9','C'),
('SWING Arcus 2 RS','SWING Arcus 2 RS','B'),
('SKYWALK Chili 3','SKYWALK Chili 3','B'),
('SKY PARAGLIDERS Apollo 2','SKY Apollo 2','B'),
('AIRDESIGN Vivo','AIRDESIGN Vivo','B'),
('ADVANCE Epsilon 7','ADVANCE Epsilon 7','B'),
('NOVA Mentor 3','NOVA Mentor 3','B'),
('AXIS Comet 3','AXIS Comet 3','B'),
('PHI Symphonia','PHI Symphonia','A'),
('MAC PARA Eden 6','MACPARA Eden 6','B'),
('NOVA AONIC','NOVA AONIC','A'),
('SKYWALK Mescal 6','SKYWALK Mescal 6','A'),
('NIVIUK Hook 4','NIVIUK Hook 4','B'),
('GIN GLIDERS Atlas 2','GIN Atlas 2','B'),
('MAC PARA Illusion','MACPARA Illusion','B'),
('MAC PARA Illusion 2','MACPARA Illusion 2','B'),
('MACPARA Illusion','MACPARA Illusion','B'),
('GIN GLIDERS Sprint 3','GIN Sprint 3','B'),
('NOVA MENTOR 7','NOVA MENTOR 7','B'),
('NOVA MENTOR7 Light','NOVA MENTOR 7 light','B'),
('NOVA Mentor 4 light','NOVA Mentor 4 light','B'),
('AIR DESIGN Volt 4','AIRDESIGN Volt 4','C'),
('AIRDESIGN Volt4','AIRDESIGN Volt 4','C'),
('NIVIUK Artik6','NIVIUK Artik 6','C'),
('NIVIUK Artik5','NIVIUK Artik 5','C'),
('GIN Bonanza 3','GIN Bonanza 3','C'),
('GIN Bonanza 2','GIN Bonanza 2','C'),
('GIN Bonanza3','GIN Bonanza 3','C'),
('GIN Bonanza2','GIN Bonanza 2','C'),
('ADVANCE Sigma11','ADVANCE Sigma 11','C'),
('ADVANCE Sigma10','ADVANCE Sigma 10','C'),
('ADVANCE Sigma 8','ADVANCE Sigma 8','C'),
('ADVANCE Pi 3','ADVANCE Pi 3','B'),
('SKYWALK Spice','SKYWALK Spice','C'),
('UP Dena','UP Dena','A'),
('UP Lhotse 2','UP Lhotse 2','B'),
('OZONE Geo 5','OZONE Geo 5','B'),
('NIVIUK Ikuma','NIVIUK Ikuma','B'),
('NOVA Ion 3','NOVA Ion 3','B'),
('SUPAIR Leaf 2 Light','SUPAIR Leaf 2 Light','B'),
('GIN GLIDERS Carrera','GIN Carrera','B'),
('UP Kibo','UP Kibo','B'),
('ADVANCE Iota2','ADVANCE Iota 2','B'),
('SKYWALK Chili5','SKYWALK Chili 5','B'),
('SKYWALK Chili4','SKYWALK Chili 4','B'),
('NIVIUK Koyot 4','NIVIUK Koyot 4','A'),
('DAVINCI Funky','DAVINCI Funky','B'),
('NIVIUK Hook 3','NIVIUK Hook 3','B'),
('SUPAIR Leaf 2','SUPAIR Leaf 2','B'),
('DUDEK Optic 2','DUDEK Optic 2','B'),
('SOL SPORTS Sycross 2','SOL Sycross 2','B'),
('BGD Magic','BGD Magic','A'),
('TRIPLE SEVEN Rook 2','777 Rook 2','B'),
('GIN GLIDERS Avid','GIN Avid','B'),
('SKY PARAGLIDERS Kudos 2','SKY Kudos 2','B'),
('MAC PARA Elan','MACPARA Elan','C'),
('U-TURN Vision','UTURN Vision','B'),
('BGD Riot','BGD Riot','B'),
('SWING Arcus RS','SWING Arcus RS','B'),
('GRADIENT Aspen 4','GRADIENT Aspen 4','C'),
('GIN GLIDERS Atlas','GIN  Atlas','B'),
('AXIS Comet 4','AXIS Comet 4','B'),
('SWING Miura RS','SWING Miura RS','B'),
('GRADIENT Golden 4','GRADIENT Golden 4','B'),
('GRADIENT Golden 5','GRADIENT Golden 5','B'),
('SKYMAN CrossCountry 2','SKYMAN CrossCountry 2','B'),
('FLOW PARAGLIDERS Cosmos','FLOW Cosmos','B'),
('AXIS Vega 5','AXIS Vega 5','C'),
('SKY PARAGLIDERS Kudos','SKY Kudos','B'),
('NIVIUK Hook 6 P','NIVIUK Hook 6 P','B'),
('AIRDESIGN Eazy 2','AIRDESIGN Eazy 2','A'),
('DUDEK Nemo 4','DUDEK Nemo 4','A'),
('AIRDESIGN VOLT','AIRDESIGN VOLT','C'),
('SOL SPORTS LT 2','SOL LT 2','C'),
('SKYWALK Mescal 5','SKYWALK Mescal 5','A'),
('OZONE Alpina','OZONE Alpina','C'),
('OZONE Mojo 6','OZONE Mojo 6','A'),
('SWING Nyos','SWING Nyos','B'),
('ADVANCE Alpha 5','ADVANCE Alpha 5','A'),
('U-TURN Infinity 5','UTURN Infinity 5','B'),
('DRIFT Carancho','DRIFT Carancho','A'),
('TRIPLE SEVEN R-light 3','777 R-light 3','B'),
('ADVANCE Pi 2','ADVANCE Pi 2','B'),
('Gin Camino','GIN Camino','C'),
('DUDEK Colt 2','DUDEK Colt 2','C'),
('UP Trango XC3','UP Trango XC3','C'),
('TRIPLE SEVEN Queen','777 Queen','C'),
('GIN GLIDERS Bolero 6','GIN Bolero 6','A'),
('BGD Adam','BGD Adam','A'),
('DAVINCI Classic','DAVINCI Classic','B'),
('NOVA Triton 2','NOVA Triton 2','C'),
('Gin Explorer','GIN Explorer','B'),
('NOVA Mentor 3 light','NOVA Mentor 3 light','B'),
('GIN Calypso','GIN Calypso','B'),
('SKY COUNTRY Discovery 5','SKYCOUNTRY Discovery 5','B'),
('UP Summit XC3','UP Summit XC3','B'),
('TRIPLE SEVEN Queen 3','777 Queen 3','C'),
('EL SPEEDO Freddie 2','ELSPEEDO Freddie 2','B'),
('BGD Echo','BGD Echo','B'),
('SWING Mito','SWING Mito','A'),
('TRIPLE SEVEN Knight 2','777 Knight 2','B'),
('MAC PARA Muse 5','MACPARA Muse 5','A'),
('OZONE Rush5','OZONE Rush 5','B'),
('U-TURN Blacklight 2','UTURN Blacklight 2','B'),
('SKYWALK Arriba 4','SKYWALK Arriba 4','B'),
('SKY PARAGLIDERS Apollo','SKY Apollo','B'),
('NIVIUK Ikuma P','NIVIUK Ikuma P','B'),
('INDEPENDENCE Geronimo 2','INDEPENDENCE Geronimo 2','B'),
('AIRDESIGN Volt 2','AIRDESIGN Volt 2','C'),
('SUPAIR Birdy','SUPAIR Birdy','A'),
('PHI Viola','PHI Viola','A'),
('NOVA Mentor 2','NOVA Mentor 2','B'),
('BGD Echo 2','BGD Echo 2','B'),
('UP Summit X','UP Summit X','B'),
('SKY COUNTRY Mystic 4','SKYCOUNTRY Mystic 4','C'),
('OZONE Rush Six','OZONE Rush 6','B'),
('OZONE Rush6','OZONE Rush 6','B'),
('OZONE Delta4','OZONE Delta 4','C'),
('Ozone Swift6','OZONE SwiftSix','B'),
('OZONE Swift Six','OZONE SwiftSix','B'),
('Ozone Delta3','OZONE Delta 3','C'),
('Ozone Swift5','OZONE Swift 5','B'),
('OZONE Mojo6','OZONE Mojo 6','A'),
('Ozone Geo6','OZONE Geo 6','B'),
('OZONE BuzzZ6','OZONE Buzz Z6','B'),
('Ozone RushSix','OZONE Rush 6','B'),
('OZONE Buzz6','OZONE Buzz Z6','B'),
('SKYWALK Chilli 5','SKYWALK Chili 5','B'),
('SKYWALK Chilli 3','SKYWALK Chili 3','B'),
('SKYWALK Chilli 4','SKYWALK Chili 4','B'),
('NIVIUK Hook5','NIVIUK Hook 5','B'),
('NIVIUK Ikuma2','NIVIUK Ikuma 2','B'),
('Niviuk Ikuma 2P','Niviuk Ikuma 2 P','B'),
('NIVIUK Artic R','NIVIUK Artik R','C'),  -- 2liner
('GIN GLIDERS Evora','GIN Evora','B'),
('GIN Evora','GIN Evora','B'),
('GIN Explorer2','GIN Explorer 2','B'),
('GIN Atlas','GIN Atlas','B'),
('PHI Maestro2','PHI Maestro 2','B'),
('PHI Maestro xalps','PHI Maestro Xalps','B'),
('PHI Maestro X Alps','PHI Maestro Xalps','B'),
('Nova Ion4','NOVA Ion 4','B'),
('Nova Ion5','NOVA Ion 4','B'),
('BGD Base2','BGD Base 2','B'),
('BGD Cure2','BGD Cure 2','C'),
('BGD Epic2','BGD Epic 2','B'),
('BGD Base2 lite','BGD Base 2 Lite','B'),
('BGD Base2 light','BGD Base 2 Lite','B'),
('AIRDESIGN Soar M','AIRDESIGN Soar','B'),
('AirDesign Rise4','AIRDESIGN Rise 4','B'),
('MACPARA Eden 7','MACPARA Eden 7','B'),
('MAC PARA Eden7','MACPARA Eden 7','B'),
('777 Rook3','777 Rook 3','B'),
('777 Rook 3','777 Rook 3','B'),
('777 Knight','777 Knight','B'),
('FLOW Fusion','FLOW Fusion','C'),
('FLOW Freedom 2','FLOW Freedom 2','B'),
('FLOW Fusion Light','FLOW Fusion Light','C');

INSERT INTO temp_gliders(glider,glider_norm,class)
VALUES
('SKY PARAGLIDERS Merlin','DRIFT Merlin','C'),
('NOVA CODEX','NOVA CODEX','C'), -- 2liner
('NIVIUK Ikuma 3','NIVIUK Ikuma 3','B'),
('AIRDESIGN Volt 5','AIRDESIGN Volt 5','C'), -- 2liner
('MAC PARA Verve','MACPARA Verve','C'),  -- 2liner
('PHI Scala 2 light','PHI Scala 2 light','C'),  -- 2liner
('NIVIUK Ikuma 3 P','NIVIUK Ikuma 3 P','B'),
('NIVIUK Ikuma 3P','NIVIUK Ikuma 3 P','B'),
('GIN GLIDERS Camino 2','GIN Camino 2','C'), -- 2liner
('PHI Scala 2','PHI Scala 2','C'),  -- 2liner
('ZOOM PARAGLIDERS X2C','ZOOM X2C','C'),  -- 2liner
('ZOOM X2C','ZOOM X2C','C'),
('artik r','NIVIUK Artik R','C'),
('ADVANCE Theta ULS','ADVANCE Theta ULS','B'),
('OZONE Buzz Z7','OZONE Buzz Z7','B'),
('NOVA Ion 7','NOVA Ion 7','B'),
('NOVA Ion 7 Light','NOVA Ion 7 Light','B'),
('SWING Stellar RS','SWING Stellar RS','B'),
('SUPAIR Step X','SUPAIR Step X','B'),
('AIRDESIGN Rise 5','AIRDESIGN Rise 5','B'),
('OZONE Geo 7','OZONE Geo 7','B'),
('SKYWALK Tequila 6','SKYWALK Tequila 6','B'),
('SKYWALK Arak 2','SKYWALK Arak 2','B'),
('AXIS Pluto 4','AXIS Pluto 4','A'),
('SKY PARAGLIDERS Exos 2','SKY Exos 2','C'),
('FLOW PARAGLIDERS Mystic','FLOW Mystic','C' ), -- 2liner
('NIVIUK Koyot 5','NIVIUK Koyot 5','B'),
('U-TURN Eternity','U-TURN Eternity','A'),
('PHI Tenor 2 light','PHI Tenor 2 light','B'),
('DAVINCI Funky 2','DAVINCI Funky 2','B'),
('AIRDESIGN Vivo 2','AIRDESIGN Vivo 2','B'),
('SUPAIR Leaf','SUPAIR Leaf','B')
;

INSERT INTO temp_gliders(glider,glider_norm,class)
VALUES
('OZONE Lyght','OZONE Lyght','C'), -- 2liner
('ADVANCE Sigma DLS','ADVANCE Sigma DLS','C'),
('Sigma DLS','ADVANCE Sigma DLS','C'),
('NIVIUK Artik 7 P','NIVIUK Artik 7 P','C'),
('NIVIUK Artik 7P','NIVIUK Artik 7 P','C'),
('SKYWALK Sage','SKYWALK Sage','C'), -- 2liner
('NIVIUK Artik R 2','NIVIUK Artik R 2','C'), -- 2liner
('NOVA VORTEX','NOVA VORTEX','C'), -- 2liner
('OZONE Delta 5','OZONE Delta 5','C'), -- 2liner
('GIN GLIDERS GTO 3','GIN GTO 3','C'),-- 2liner
('PHI Beat 2 Light','PHI Beat 2 Light','B'),
('Unbekannt Zoom x2c','	ZOOM X2C','C'), -- 2liner
('NIVIUK Hiko P','NIVIUK Hiko P','B'),
('BGD Base 3','BGD Base 3','B'),
('ADVANCE Theta','ADVANCE Theta','B'),
('GIN GTO3','GIN GTO 3','C'), -- 2liner
('MAC PARA Eden 8','MACPARA Eden 8','B'),
('PHI Beat 2','PHI Beat 2','B'),
('AIRDESIGN LiVi','AIRDESIGN LiVi','B'),
('TRIPLE SEVEN Rook 4','777 Rook 4','B'),
('NIVIUK Hiko','NIVIUK Hiko','B'),
('AIRDESIGN Soar 2','AIRDESIGN Soar 2','B'),
('DAVINCI Mambo','DAVINCI Mambo','C'), -- 2liner
('SKY PARAGLIDERS Apollo 3','SKY Apollo 3','B'),
('OZONE Alta','OZONE Alta','A'),
('NIVIUK Kode P','NIVIUK Kode P','A'),
('BGD Lynx2','BGD Lynx 2','C'), -- 2liner
('SUPAIR Leaf 3 Light','SUPAIR Leaf 3 Light','B'),
('SUPAIR Leaf 3','SUPAIR Leaf 3','B'),
('PHI Tenor 2','PHI Tenor 2','B'),
('SKYWALK Masala 4','SKYWALK Masala 4','A'),
('UP Kibo X','UP Kibo X','B'),
('APCO AVIATION Nestra Light','APCO Nestra Light','B'),
('BGD Cure 3','BGD Cure 3','C'), -- 2liner
('GIN Camino 2','GIN Camino 2','C'), -- 2liner
('GIN Avid','GIN Avid','B'),
('GIN GLIDERS Calypso 2','GIN Calypso 2','B'),
('GIN GTO 3','GIN GTO 3','C'), -- 2liner
('GIN GLIDERS Bolero 7','GIN Bolero 7','A'),
('GIN Bolero 7','GIN Bolero 7','A'),
('DAVINCI Classic 2','DAVINCI Classic 2','A'),
('DAVINCI Rhythm2','DAVINCI Rhythm2','A'),
('UP Lhotse','UP Lhotse','B'),
('UP Kangri X','UP Kangri X','B'),
('UP Rimo','UP Rimo','A'),
('SOL SPORTS Atmus 3','SOL Atmus 3','B'),
('PHI Symphonia 2 light','PHI Symphonia 2 light','A'),
('NERVURES Spantik 2','NERVURES Spantik 2','B'),
('ADVANCE Sigma 7','ADVANCE Sigma 7','C'),
('Advance Sigma 12','Advance Sigma DLS','C'),
('Advance IotaDLS', 'ADVANCE Iota DLS','B'),
('Advance Epsilon9', 'ADVANCE Epsilon 9','B'),
('ADVANCE Theta ULS 25', 'ADVANCE Theta ULS','B'),
('Advance Sigma DLS 24', 'Advance Sigma DLS','C'),
('Advance Iota DLS 25', 'ADVANCE Iota DLS','B'),
('Advance Epsilon 10 DLS', 'ADVANCE Epsilon DLS','B'),
('WAY Ruby','WAY Ruby','B'),
('NIVIUK Artik 3','NIVIUK Artik 3','C'),
('NIVIUK Ikuma3','NIVIUK Ikuma 3','B'),
('NIVIUK Hook 6P','NIVIUK Hook 6 P','B'),
('NIVIUK Hook6','NIVIUK Hook 6','B'),
('NIVIUK Artik R2','NIVIUK Artik R 2','C'), -- 2liner
('Niviuk Ikuma3p','Niviuk Ikuma 3 P','B'),
('NIVIUK ArtikR','NIVIUK Artik R','C'), -- 2liner
('Niviuk Ikuma P 3','Niviuk Ikuma 3 P','B'),
('Niviuk Artik 7','NIVIUK Artik 7 P','C'),
('NIVIUK Niviuk ikuma 3p','Niviuk Ikuma 3 P','B'),
('BGD Breeze','BGD Breeze','B'),
('BGD Base Lite','BGD Base Lite','B'),
('BGD Cure3','BGD Cure 3','C'), -- 2liner
('GRADIENT Nevada','GRADIENT Nevada','B'),
('FLOW PARAGLIDERS F2 Light','FLOW F2 Light','B'),
('FLOW PARAGLIDERS Mystic+','FLOW Mystic+','C'), -- 2liner
('FLOW Mystic','FLOW Mystic','C'), -- 2liner
('FLOW Cosmos 2','FLOW Cosmos 2','B'),
('FLOW Mystic+','FLOW Mystic+','C'), --2liner
('FLOW PARAGLIDERS Cosmos 2','FLOW Cosmos 2','B'),
('FLOW Mystic +','FLOW Mystic+','C'), --2liner
('FLOW Cosmos2','FLOW Cosmos 2','B'),
('Flow Paragliders Freedom2','FLOW Freedom 2','B'),
('Photon','OZONE Photon','C'), --2liner
('SKYWALK Arak Air2','SKYWALK Arak Air2','B'),
('SWING Serac RS','SWING Serac RS','B'),
('SWING Serac','SWING Serac RS','B'),
('SOL SPORTS Sycross','SOL Sycross','B'),
('SOL SPORTS Atmus 2','SOL Atmus 2','B'),
('SKYWALK Mescal 4','SKYWALK Mescal 4','A'),
('Skywalk Cumeo2','Skywalk Cumeo 2','B'),
('SKYWALK Masala3','SKYWALK Masala 3','A'),
('SKYWALK Cayenne 4','SKYWALK Cayenne 4','C'),
('SKYWALK Arriba 3','SKYWALK Arriba 3','B'),
('SKYWALK ArakAir','SKYWALK Arak Air','B'),
('Skywalk Arak2','Skywalk Arak 2','B'),
('SKYWALK Tequila6','SKYWALK Tequila 6','B'),
('NOVA ION 2','NOVA ION 2','B'),
('NOVA AONIC Light','NOVA AONIC Light','A'),
('NOVA Mentor 7 L','NOVA Mentor 7','B'),
('Nova Ion7','Nova Ion 7','B'),
('Nova Ion7light','NOVA Ion 7 Light','B'),
('Nova Ion7 light','NOVA Ion 7 Light','B'),
('NOVA Mentor7','NOVA Mentor 7','B'),
('Nova Vortex M','Nova Vortex','C'), -- 2liner
('Nova Vortex XXS','Nova Vortex','C'), -- 2liner
('NOVA Vortex MS','Nova Vortex','C'), -- 2liner
('PHI Scala2','PHI Scala 2','C' ), -- 2liner
('PHI Symphonia2','PHI Symphonia 2','A'),
('PHI Symphonia Light 2', 'PHI Symphonia 2 light','A'),
('AIR DESIGN Volt 5','AIRDESIGN Volt 5','C'), -- 2liner
('AIRDESIGN Volt5','AIRDESIGN Volt 5','C'), -- 2liner
('AIR DESIGN Rise 5','AIRDESIGN Rise 5','B'),
('AIRDESIGN Soar2','AIRDESIGN Soar 2','B'),
('SUPAIR Eona 3','SUPAIR Eona 3','A'),
('Mac Para Verve 25','MACPARA VERVE','C'), -- 2liner
('MACPARA VERVE','MACPARA VERVE','C'), -- 2liner
('MAC PARA Aravis','MAC PARA Aravis','A'), -- h&f
('Arak Air','SKYWALK Arak Air','B'),
('PROFLY Leeloo 2','PROFLY Leeloo 2','B')


;

--DELETE FROM gliders;

INSERT INTO gliders (glider, class, glider_norm)
SELECT t.glider, t.class, t.glider_norm
FROM temp_gliders t
WHERE NOT EXISTS (
    SELECT 1 FROM gliders g WHERE g.glider=t.glider COLLATE NOCASE
);
