CREATE TABLE IF NOT EXISTS pilots
               (
                [year] int not null,
                xc_rank int not null, 
                username, 
                pilot_id);

CREATE TABLE IF NOT EXISTS flights
            (pilot_id, flight_id, launch,flight_type,flight_length,flight_points, glider, details);

CREATE TABLE IF NOT EXISTS gliders
            (glider TEXT PRIMARY KEY,class TEXT, glider_norm TEXT,UNIQUE (glider COLLATE NOCASE));


CREATE TEMPORARY TABLE temp_gliders(glider, class, glider_norm);
INSERT INTO temp_gliders(glider,glider_norm,class)
VALUES
('OZONE Alpina 4','OZONE Alpina 4','C'),
('OZONE Photon','OZONE Photon','C'),
('AIRDESIGN Volt 4','AIRDESIGN Volt 4','C'),
('NIVIUK Artik R','NIVIUK Artik R','C'),
('OZONE Delta 4','OZONE Delta 4','C'),
('ADVANCE Sigma 11','ADVANCE Sigma 11','C'),
('NOVA MENTOR 7 light','NOVA MENTOR 7 light','B'),
('FLOW PARAGLIDERS Fusion','FLOW Fusion','C'),
('NIVIUK Artik 6','NIVIUK Artik 6','C'),
('ADVANCE Iota DLS','ADVANCE Iota DLS','B'),
('OZONE Rush 6','OZONE Rush 6','B'),
('SUPAIR Savage','SUPAIR Savage','C'),
('SKYWALK Mint','SKYWALK Mint','C'),
('GIN GLIDERS Bonanza 2','GIN Bonanza 2','C'),
('GIN GLIDERS Bonanza 3','GIN Bonanza 3','C'),
('OZONE SwiftSix','OZONE SwiftSix','B'),
('OZONE Delta 3','OZONE Delta 3','C'),
('OZONE Alpina 3','OZONE Alpina 3','C'),
('PHI Maestro 2 light','PHI Maestro 2 light','B'),
('OZONE Swift 5','OZONE Swift 5','B'),
('ADVANCE Sigma 10','ADVANCE Sigma 10','C'),
('GIN GLIDERS Camino','GIN Camino','C'),
('GIN GLIDERS Explorer 2','GIN Explorer 2','B'),
('PHI Allegro X-alps','PHI Allegro Xalps','C'),
('NIVIUK Ikuma 2','NIVIUK Ikuma 2','B'),
('SKYWALK Chili 5','SKYWALK Chili 5','B'),
('OZONE Rush 5','OZONE Rush 5','B'),
('PHI Maestro 2','PHI Maestro 2','B'),
('BGD Base 2','BGD Base 2','B'),
('ADVANCE Iota 2','ADVANCE Iota 2','B'),
('BGD Cure 2','BGD Cure 2','C'),
('PHI Maestro','PHI Maestro','B'),
('NIVIUK Artik 5','NIVIUK Artik 5','C'),
('ADVANCE XI','ADVANCE XI','B'),
('SKYWALK Arak','SKYWALK Arak','B'),
('SKYWALK Arak Air','SKYWALK Arak Air','B'),
('MAC PARA Eden 7','MACPARA Eden 7','B'),
('AIRDESIGN Soar','AIRDESIGN Soar','B'),
('AXIS Venus SC','AXIS Venus SC','C'),
('GIN GLIDERS Explorer','GIN Explorer','B'),
('PHI Maestro X-alps','PHI Maestro Xalps','B'),
('TRIPLE SEVEN Rook 3','777 Rook 3','B'),
('NOVA Sector','NOVA Sector','C'),
('NOVA Mentor 5','NOVA Mentor 5','B'),
('FLOW PARAGLIDERS Fusion Light','FLOW Fusion Light','C'),
('ADVANCE Epsilon 9','ADVANCE Epsilon 9','B'),
('UP Trango X-race','UP Trango X-race','C'),
('SKYWALK Chili 4','SKYWALK Chili 4','B'),
('MAC PARA Elan 3','MACPARA Elan 3','C'),
('BGD Base 2 Lite','BGD Base 2 Lite','B'),
('SKYWALK Cayenne 6','SKYWALK Cayenne 6','C'),
('TRIPLE SEVEN Queen 2','777 Queen 2','C'),
('OZONE Delta 2','OZONE Delta 2','C'),
('PHI Beat Light','PHI Beat Light','B'),
('AIRDESIGN Rise 4','AIRDESIGN Rise 4','B'),
('ADVANCE Iota','ADVANCE Iota','B'),
('PHI Allegro','PHI Allegro','C'),
('NIVIUK Ikuma 2 P','NIVIUK Ikuma 2 P','B'),
('NOVA Mentor 6','NOVA Mentor 6','B'),
('UP Trango X','UP Trango X','C'),
('NIVIUK Hook 5','NIVIUK Hook 5','B'),
('AIRDESIGN Volt 3','AIRDESIGN Volt 3','C'),
('BGD Cure','BGD Cure','C'),
('SKYWALK Cumeo','SKYWALK Cumeo','B'),
('OZONE Buzz Z6','OZONE Buzz Z6','B'),
('NOVA Mentor 4','NOVA Mentor 4','B'),
('OZONE Geo 6','OZONE Geo 6','B'),
('PHI Beat','PHI Beat','B'),
('OZONE Rush 4','OZONE Rush 4','B'),
('SWING Nyos RS','SWING Nyos RS','B'),
('MAC PARA Elan 2','MACPARA Elan 2','C'),
('ADVANCE Epsilon 8','ADVANCE Epsilon 8','B'),
('DRIFT Hawk','DRIFT Hawk','B'),
('DAVINCI Tango','DAVINCI Tango','C'),
('NOVA Ion 6','NOVA Ion 6','B'),
('OZONE Alpina 2','OZONE Alpina 2','C'),
('UP Kangri','UP Kangri','B'),
('BGD Punk','BGD Punk','B'),
('SKYWALK Cayenne 5','SKYWALK Cayenne 5','C'),
('FLOW PARAGLIDERS Freedom 2','FLOW Freedom 2','B'),
('OZONE Swift 4','OZONE Swift 4','B'),
('SWING Helios RS','SWING Helios RS','C'),
('SKYWALK Tequila 5','SKYWALK Tequila 5','B'),
('NIVIUK Hook 6','NIVIUK Hook 6','B'),
('UP Summit XC4','UP Summit XC4','B'),
('NOVA Ion 5','NOVA Ion 5','B'),
('NIVIUK Artik 4','NIVIUK Artik 4','C'),
('BGD Lynx 2','BGD Lynx 2','C'),
('NOVA Phantom','NOVA Phantom','B'),
('PHI Tenor Light','PHI Tenor Light','B'),
('SKYWALK Cumeo 2','SKYWALK Cumeo 2','B'),
('ADVANCE Epsilon DLS','ADVANCE Epsilon DLS','B'),
('BGD Base','BGD Base','B'),
('SWING Nyos 2 RS','SWING Nyos 2 RS','B'),
('BGD Lynx','BGD Lynx','C'),
('GIN Explorer 2','GIN Explorer 2','B'),
('PHI Tenor','PHI Tenor','B'),
('SUPAIR Step','SUPAIR Step','B'),
('NOVA Ion 4','NOVA Ion 4','B'),
('GRADIENT Aspen 6','GRADIENT Aspen 6','C'),
('SWING Libra RS','SWING Libra RS','C'),
('UP Kibo 2','UP Kibo 2','B'),
('GRADIENT Nevada 2','GRADIENT Nevada 2','B'),
('AXIS Vega 6','AXIS Vega 6','C'),
('OZONE Swift 6','OZONE SwiftSix','B'),
('SUPAIR Step Light','SUPAIR Step Light','B'),
('PROFLY Leeloo','PROFLY Leeloo','B'),
('NIVIUK Hook 5 P','NIVIUK Hook 5 P','B'),
('NOVA Mentor 5 light','NOVA Mentor 5 light','B'),
('TRIPLE SEVEN Q-light','777 Qlight','C'),
('SKYWALK Masala 3','SKYWALK Masala 3','A'),
('PHI Symphonia 2','PHI Symphonia 2','A'),
('GIN GLIDERS Calypso','GIN Calypso','B'),
('NOVA Ion 6 Light','NOVA Ion 6 Light','B'),
('GIN GLIDERS Carrera plus','GIN Carrera plus','B'),
('NOVA Mentor 6 Light','NOVA Mentor 6 Light','B'),
('OZONE Buzz Z5','OZONE Buzz Z5','B'),
('DRIFT Merlin','DRIFT Merlin','C'),
('SUPAIR Taska','SUPAIR Taska','C'),
('AIRDESIGN Rise 3','AIRDESIGN Rise 3','B'),
('TRIPLE SEVEN Knight','777 Knight','B'),
('SKYWALK Spice 2','SKYWALK Spice 2','C'),
('NOVA Ion 5 light','NOVA Ion 5 light','B'),
('ADVANCE Alpha 6','ADVANCE Alpha 6','A'),
('Ozone Alpina4','OZONE Alpina 4','C'),
('BGD Epic','BGD Epic','B'),
('BGD Epic 2','BGD Epic 2','B'),
('ADVANCE Alpha 7','ADVANCE Alpha 7','A'),
('SKYWALK Tequila 4','SKYWALK Tequila 4','B'),
('ADVANCE Sigma 9','ADVANCE Sigma 9','C'),
('SWING Arcus 2 RS','SWING Arcus 2 RS','B'),
('SKYWALK Chili 3','SKYWALK Chili 3','B'),
('SKY PARAGLIDERS Apollo 2','SKY Apollo 2','B'),
('AIRDESIGN Vivo','AIRDESIGN Vivo','B'),
('ADVANCE Epsilon 7','ADVANCE Epsilon 7','B'),
('NOVA Mentor 3','NOVA Mentor 3','B'),
('AXIS Comet 3','AXIS Comet 3','B'),
('PHI Symphonia','PHI Symphonia','A'),
('MAC PARA Eden 6','MACPARA Eden 6','B'),
('NOVA AONIC','NOVA AONIC','A'),
('SKYWALK Mescal 6','SKYWALK Mescal 6','A'),
('NIVIUK Hook 4','NIVIUK Hook 4','B'),
('GIN GLIDERS Atlas 2','GIN Atlas 2','B'),
('MAC PARA Illusion','MACPARA Illusion','B'),
('MAC PARA Illusion 2','MACPARA Illusion 2','B'),
('MACPARA Illusion','MACPARA Illusion','B'),
('GIN GLIDERS Sprint 3','GIN Sprint 3','B'),
('NOVA MENTOR 7','NOVA MENTOR 7','B'),
('NOVA MENTOR7 Light','NOVA MENTOR 7 Light','B'),
('NOVA Mentor 4 light','NOVA Mentor 4 light','B'),
('AIR DESIGN Volt 4','AIRDESIGN Volt 4','C'),
('AIRDESIGN Volt4','AIRDESIGN Volt 4','C'),
('NIVIUK Artik6','NIVIUK Artik 6','C'),
('NIVIUK Artik5','NIVIUK Artik 5','C'),
('GIN Bonanza 3','GIN Bonanza 3','C'),
('GIN Bonanza 2','GIN Bonanza 2','C'),
('GIN Bonanza3','GIN Bonanza 3','C'),
('GIN Bonanza2','GIN Bonanza 2','C'),
('ADVANCE Sigma11','ADVANCE Sigma 11','C'),
('ADVANCE Sigma10','ADVANCE Sigma 10','C'),
('ADVANCE Sigma 8','ADVANCE Sigma 8','C'),
('ADVANCE Pi 3','ADVANCE Pi 3','B'),
('SKYWALK Spice','SKYWALK Spice','C'),
('UP Dena','UP Dena','A'),
('UP Lhotse 2','UP Lhotse 2','B'),
('OZONE Geo 5','OZONE Geo 5','B'),
('NIVIUK Ikuma','NIVIUK Ikuma','B'),
('NOVA Ion 3','NOVA Ion 3','B'),
('SUPAIR Leaf 2 Light','SUPAIR Leaf 2 Light','B'),
('GIN GLIDERS Carrera','GIN Carrera','B'),
('UP Kibo','UP Kibo','B'),
('ADVANCE Iota2','ADVANCE Iota 2','B'),
('SKYWALK Chili5','SKYWALK Chili 5','B'),
('SKYWALK Chili4','SKYWALK Chili 4','B'),
('NIVIUK Koyot 4','NIVIUK Koyot 4','A'),
('DAVINCI Funky','DAVINCI Funky','B'),
('NIVIUK Hook 3','NIVIUK Hook 3','B'),
('SUPAIR Leaf 2','SUPAIR Leaf 2','B'),
('DUDEK Optic 2','DUDEK Optic 2','B'),
('SOL SPORTS Sycross 2','SOL Sycross 2','B'),
('BGD Magic','BGD Magic','A'),
('TRIPLE SEVEN Rook 2','777 Rook 2','B'),
('GIN GLIDERS Avid','GIN Avid','B'),
('SKY PARAGLIDERS Kudos 2','SKY Kudos 2','B'),
('MAC PARA Elan','MACPARA Elan','C'),
('U-TURN Vision','UTURN Vision','B'),
('BGD Riot','BGD Riot','B'),
('SWING Arcus RS','SWING Arcus RS','B'),
('GRADIENT Aspen 4','GRADIENT Aspen 4','C'),
('GIN GLIDERS Atlas','GIN GLIDERS Atlas','B'),
('AXIS Comet 4','AXIS Comet 4','B'),
('SWING Miura RS','SWING Miura RS','B'),
('GRADIENT Golden 4','GRADIENT Golden 4','B'),
('GRADIENT Golden 5','GRADIENT Golden 5','B');



--DELETE FROM gliders;

INSERT INTO gliders (glider, class, glider_norm)
SELECT t.glider, t.class, t.glider_norm
FROM temp_gliders t
WHERE NOT EXISTS (
    SELECT 1 FROM gliders g WHERE g.glider=t.glider COLLATE NOCASE
);
